tests: Fix build failure caused by C99 use
Build failure in Continuous:

../../test/test-file-utilities-get-common-filename-prefix.c: In function
'test_many_strings':
../../test/test-file-utilities-get-common-filename-prefix.c:366:9:
error: 'for' loop initial declarations are only allowed in C99 or C11
mode
         for (int i = 0; i < 500; ++i) {