Fix libm linking
Nautilus was underlinked, found by recently introduced change in Fedora:
https://fedoraproject.org/wiki/Features/ChangeInImplicitDSOLinking

/usr/bin/ld: ../libnautilus-private/.libs/libnautilus-private.a(eel-canvas.o): undefined reference to symbol 'floor@@GLIBC_2.0'
/usr/bin/ld: note: 'floor@@GLIBC_2.0' is defined in DSO /lib/libm.so.6 so try adding it to the linker command line
/lib/libm.so.6: could not read symbols: Invalid operation